In [7]:
!pip install pandas numpy tensorflow scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: tensorflow in /opt/anaconda3/lib/python3.11/site-packages (2.16.2)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.11/site-packages (3.8.0)
Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.11/site-packages (0.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: absl-py>=1.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (3.16.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.3.1 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (0.3.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (23.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (2.31.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (68.2.2)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (1.83.1)
Requirement already satisfied: tensorboard<2.17,>=2.16 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (2.16.2)
Requirement already satisfied: keras>=3.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/anaconda3/lib/python3.11/site-packages (from tensorflow) (0.37.1)
Requirement already satisfied: scipy>=1.3.2 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.41.2)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.11/site-packages (from keras>=3.0.0->tensorflow) (13.3.5)
Requirement already satisfied: namex in /opt/anaconda3/lib/python3.11/site-packages (from keras>=3.0.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /opt/anaconda3/lib/python3.11/site-packages (from keras>=3.0.0->tensorflow) (0.20.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2024.2.2)
Requirement already satisfied: markdown>=2.6.8 in /opt/anaconda3/lib/python3.11/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/anaconda3/lib/python3.11/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (2.2.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/anaconda3/lib/python3.11/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich->keras>=3.0.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.11/site-packages (from rich->keras>=3.0.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=3.0.0->tensorflow) (0.1.0)

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [26]:
file_path = "downloads/Grocery_Dataset.csv"
df = pd.read_csv(file_path)
df.head()

,Product_ID,Product_Name,Catagory,Supplier_ID,Supplier_Name,Stock,Reorder_Level,Reorder_Quantity,Price,Date_Received
0,29-205-1132,Sushi Rice,Grains & Pulses,38-037-1699,Jaxnation,22.0,72.0,70.0,NaN,8/16/2024
1,40-681-9981,Arabica Coffee,Beverages,54-470-2479,Feedmix,45.0,77.0,2.0,NaN,11/1/2024
2,06-955-3428,Black Rice,Grains & Pulses,54-031-2945,Vinder,30.0,38.0,83.0,NaN,8/3/2024
3,71-594-6552,Long Grain Rice,Grains & Pulses,63-492-7603,Brightbean,12.0,59.0,62.0,NaN,12/8/2024
4,57-437-1828,Plum,Fruits & Vegetables,54-226-4308,Topicstorm,37.0,30.0,74.0,NaN,7/3/2024

In [27]:
# Missing values hatayein aur Needs_Reorder column banayein
df = df.drop(columns=['Price'], errors='ignore').dropna(subset=['Stock', 'Reorder_Level', 'Reorder_Quantity', 'Catagory'])
df['Needs_Reorder'] = (df['Stock'] <= df['Reorder_Level']).astype(int)

df[['Catagory', 'Stock', 'Reorder_Level', 'Needs_Reorder']].head()

              Catagory  Stock  Reorder_Level  Needs_Reorder
0      Grains & Pulses   22.0           72.0              1
1            Beverages   45.0           77.0              1
2      Grains & Pulses   30.0           38.0              1
3      Grains & Pulses   12.0           59.0              1
4  Fruits & Vegetables   37.0           30.0              0

In [28]:
X = df[['Catagory', 'Stock', 'Reorder_Level', 'Reorder_Quantity']]
y = df['Needs_Reorder']

# Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("Training rows:", len(X_train), "| Testing rows:", len(X_test))

Training rows: 786 | Testing rows: 197

In [29]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Stock', 'Reorder_Level', 'Reorder_Quantity']),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['Catagory'])
    ]
)

X_train_proc = preprocessor.fit_transform(X_train)
X_test_proc = preprocessor.transform(X_test)
print("Processed Features Shape:", X_train_proc.shape)

Processed Features Shape: (786, 10)

In [30]:
model = Sequential([
    Input(shape=(X_train_proc.shape[1],)),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,329 (13.00 KB)

 Trainable params: 3,329 (13.00 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
history = model.fit(
    X_train_proc, y_train,
    epochs=30,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.7659 - loss: 0.6247 - val_accuracy: 0.8861 - val_loss: 0.5208
Epoch 2/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8981 - loss: 0.4071 - val_accuracy: 0.9430 - val_loss: 0.2672
Epoch 3/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9331 - loss: 0.1978 - val_accuracy: 0.9873 - val_loss: 0.1387
Epoch 4/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9506 - loss: 0.1389 - val_accuracy: 0.9873 - val_loss: 0.1007
Epoch 5/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9713 - loss: 0.1020 - val_accuracy: 0.9873 - val_loss: 0.0832
Epoch 6/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9713 - loss: 0.0823 - val_accuracy: 0.9810 - val_loss: 0.0763
Epoch 7/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9729 - loss: 0.0765 - val_accuracy: 0.9810 - val_loss: 0.0641
Epoch 8/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9729 - loss: 0.0648 - val_accuracy: 0.9810 - val_loss: 0.0576
Epoch 9/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9745 - loss: 0.0602 - val_accuracy: 0.9873 - val_loss: 0.0583
Epoch 10/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9666 - loss: 0.0676 - val_accuracy: 0.9810 - val_loss: 0.0591
Epoch 11/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9857 - loss: 0.0531 - val_accuracy: 0.9810 - val_loss: 0.0499
Epoch 12/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9729 - loss: 0.0601 - val_accuracy: 0.9747 - val_loss: 0.0614
Epoch 13/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9729 - loss: 0.0544 - val_accuracy: 0.9873 - val_loss: 0.0523
Epoch 14/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0624 - val_accuracy: 0.9873 - val_loss: 0.0520
Epoch 15/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9825 - loss: 0.0479 - val_accuracy: 0.9873 - val_loss: 0.0496
Epoch 16/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9809 - loss: 0.0445 - val_accuracy: 0.9747 - val_loss: 0.0453
Epoch 17/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9873 - loss: 0.0392 - val_accuracy: 0.9747 - val_loss: 0.0472
Epoch 18/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9777 - loss: 0.0478 - val_accuracy: 0.9873 - val_loss: 0.0424
Epoch 19/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9761 - loss: 0.0442 - val_accuracy: 0.9873 - val_loss: 0.0489
Epoch 20/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9841 - loss: 0.0430 - val_accuracy: 0.9937 - val_loss: 0.0378
Epoch 21/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9873 - loss: 0.0365 - val_accuracy: 0.9810 - val_loss: 0.0466
Epoch 22/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9873 - loss: 0.0352 - val_accuracy: 0.9810 - val_loss: 0.0441
Epoch 23/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9904 - loss: 0.0319 - val_accuracy: 0.9810 - val_loss: 0.0433
Epoch 24/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9873 - loss: 0.0326 - val_accuracy: 0.9873 - val_loss: 0.0417
Epoch 25/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9857 - loss: 0.0431 - val_accuracy: 0.9747 - val_loss: 0.0456
Epoch 26/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9777 - loss: 0.0450 - val_accuracy: 0.9684 - val_loss: 0.0517
Epoch 27/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9777 - loss: 0.0436 - val_accuracy: 0.9747 - val_loss: 0.0344
Epoch 28/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9904 - loss: 0.0289 - val_accuracy: 0.9810 - val_loss: 0.0415
Epoch 29/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9889 - loss: 0.0258 - val_accuracy: 0.9937 - val_loss: 0.0383
Epoch 30/30
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9841 - loss: 0.0304 - val_accuracy: 0.9810 - val_loss: 0.0341

In [32]:
loss, accuracy = model.evaluate(X_test_proc, y_test, verbose=0)
print(f"Final Model Accuracy: {accuracy * 100:.2f}%")

# Naye item par prediction testing
def predict_stock(category, stock, reorder_level, reorder_qty):
    sample = pd.DataFrame([{'Catagory': category, 'Stock': stock, 'Reorder_Level': reorder_level, 'Reorder_Quantity': reorder_qty}])
    sample_proc = preprocessor.transform(sample)
    prob = model.predict(sample_proc, verbose=0)[0][0]
    return "REORDER NEEDED" if prob > 0.5 else "STOCK SUFFICIENT", prob

status, score = predict_stock('Beverages', stock=10.0, reorder_level=50.0, reorder_qty=40.0)
print(f"Prediction Result: {status} (Confidence: {score:.2f})")

Final Model Accuracy: 99.49%
Prediction Result: REORDER NEEDED (Confidence: 1.00)

In [33]:
import os
print([f for f in os.listdir() if f.endswith(('.keras', '.joblib'))])
print([f for f in os.listdir('downloads') if f.endswith(('.keras', '.joblib'))])

['.keras']
[]

In [36]:
import joblib

model.save("grocery_ann_model.keras")
model.save("downloads/grocery_ann_model.keras")

joblib.dump(preprocessor, "preprocessor.joblib")
joblib.dump(preprocessor, "downloads/preprocessor.joblib")

print("Files saved successfully in all paths!")

Files saved successfully in all paths!

In [35]:
import os
print([f for f in os.listdir() if f.endswith(('.keras', '.joblib'))])

['preprocessor.joblib', 'grocery_ann_model.keras', '.keras']